In [1]:
import pandas as pd
import numpy as np

In [2]:
# Upload data
 
data = pd.read_excel("nftr12.xlsx", sheet_name='Sheet 1')
data.head(14)

,SECTOR (Labels),SECTOR (Labels).1,Non-financial corporations,Non-financial corporations.1,Financial corporations,Financial corporations.1,General government,General government.1,Households; non-profit institutions serving households,Households; non-profit institutions serving households.1,Rest of the world,Rest of the world.1
0,DIRECT (Labels),DIRECT (Labels),Paid,Received,Paid,Received,Paid,Received,Paid,Received,Paid,Received
1,P1,Output,:,434543,:,24259,:,64991,:,82750,:,:
2,P1O,"Market output, output for final use and paymen...",:,:,:,:,:,13482,:,:,:,:
3,P11,Market output,:,427687,:,24027,:,2505,:,51502,:,:
4,P12,Output for own final use,:,6856,:,233,:,2905,:,23121,:,:
5,P13,Other non-market output,:,:,:,:,:,59581,:,8126,:,:
6,P2,Intermediate consumption,261220,:,12019,:,20620,:,29136,:,:,:
7,P3,Final consumption expenditure,:,:,:,:,63287,:,170351,:,:,:
8,P31,Individual consumption expenditure,:,:,:,:,38849,:,170351,:,:,:
9,P32,Collective consumption expenditure,:,:,:,:,24438,:,:,:,:,:
10,P4,Actual final consumption,:,:,:,:,:,:,209200,:,:,:
11,P4_R_HAB,Actual final consumption in real terms per capita,:,:,:,:,:,:,23505,:,:,:
12,P5G,Gross capital formation,45923,:,2180,:,9364,:,18642,:,:,:
13,P51G,Gross fixed capital formation,43843,:,2166,:,9358,:,16806,:,:,:

In [3]:
# Rename columns
data.rename(columns = {'SECTOR (Labels)': 'codes'},inplace=True)
data.rename(columns = {'Non-financial corporations': 'NFC-'},inplace=True)
data.rename(columns = {'Non-financial corporations.1': 'NFC+'},inplace=True)
data.rename(columns = {'Financial corporations': 'FC-'},inplace=True)
data.rename(columns = {'Financial corporations.1': 'FC+'},inplace=True)
data.rename(columns = {'Public financial corporations': 'PC-'},inplace=True)
data.rename(columns = {'Public financial corporations.1': 'PC+'},inplace=True)
data.rename(columns = {'General government': 'Gov-'},inplace=True)
data.rename(columns = {'General government.1': 'Gov+'},inplace=True)
data.rename(columns = {'Households; non-profit institutions serving households': 'HH-'},inplace=True)
data.rename(columns = {'Households; non-profit institutions serving households.1': 'HH+'},inplace=True)
data.rename(columns = {'Rest of the world': 'RoW-'},inplace=True)
data.rename(columns = {'Rest of the world.1': 'RoW+'},inplace=True)
data.rename(columns = {'SECTOR (Labels).1': 'item/sectors'},inplace=True)
#data.rename(columns={0 :'items/sectors'}, inplace=True )
data

,codes,item/sectors,NFC-,NFC+,FC-,FC+,Gov-,Gov+,HH-,HH+,RoW-,RoW+
0,DIRECT (Labels),DIRECT (Labels),Paid,Received,Paid,Received,Paid,Received,Paid,Received,Paid,Received
1,P1,Output,:,434543,:,24259,:,64991,:,82750,:,:
2,P1O,"Market output, output for final use and paymen...",:,:,:,:,:,13482,:,:,:,:
3,P11,Market output,:,427687,:,24027,:,2505,:,51502,:,:
4,P12,Output for own final use,:,6856,:,233,:,2905,:,23121,:,:
...,...,...,...,...,...,...,...,...,...,...,...,...
129,P51G_N1122G,"Assets, gross - other structures",:,:,:,:,:,:,:,:,:,:
130,P51G_N1122G_CLV2010,"Assets, gross - other structures - chain linke...",:,:,:,:,:,:,:,:,:,:
131,P51G_N112G,"Assets, gross - other buildings and structures",:,:,:,:,:,:,:,:,:,:
132,P51G_N112G_CLV2010,"Assets, gross - other buildings and structures...",:,:,:,:,:,:,:,:,:,:
133,P51G_N11G_CLV2010,"Assets, gross - fixed assets by type of asset ...",:,:,:,:,:,:,:,:,:,:

In [4]:
data = data.set_index('item/sectors')

In [5]:
data.head()

,codes,NFC-,NFC+,FC-,FC+,Gov-,Gov+,HH-,HH+,RoW-,RoW+
item/sectors,,,,,,,,,,,
DIRECT (Labels),DIRECT (Labels),Paid,Received,Paid,Received,Paid,Received,Paid,Received,Paid,Received
Output,P1,:,434543,:,24259,:,64991,:,82750,:,:
"Market output, output for final use and payments for other non-market output",P1O,:,:,:,:,:,13482,:,:,:,:
Market output,P11,:,427687,:,24027,:,2505,:,51502,:,:
Output for own final use,P12,:,6856,:,233,:,2905,:,23121,:,:

In [6]:
# replace b with c
data = data.replace(':', '0')
data.head()

,codes,NFC-,NFC+,FC-,FC+,Gov-,Gov+,HH-,HH+,RoW-,RoW+
item/sectors,,,,,,,,,,,
DIRECT (Labels),DIRECT (Labels),Paid,Received,Paid,Received,Paid,Received,Paid,Received,Paid,Received
Output,P1,0,434543,0,24259,0,64991,0,82750,0,0
"Market output, output for final use and payments for other non-market output",P1O,0,0,0,0,0,13482,0,0,0,0
Market output,P11,0,427687,0,24027,0,2505,0,51502,0,0
Output for own final use,P12,0,6856,0,233,0,2905,0,23121,0,0

In [7]:
data = data.drop(index=('DIRECT (Labels)'))
data.head()

,codes,NFC-,NFC+,FC-,FC+,Gov-,Gov+,HH-,HH+,RoW-,RoW+
item/sectors,,,,,,,,,,,
Output,P1,0,434543,0,24259,0,64991,0,82750,0,0
"Market output, output for final use and payments for other non-market output",P1O,0,0,0,0,0,13482,0,0,0,0
Market output,P11,0,427687,0,24027,0,2505,0,51502,0,0
Output for own final use,P12,0,6856,0,233,0,2905,0,23121,0,0
Other non-market output,P13,0,0,0,0,0,59581,0,8126,0,0

In [8]:
data.to_csv('au_nf12.csv')

In [9]:
df = pd.read_csv('au_nf12.csv')
df = df.set_index('item/sectors')
df

,codes,NFC-,NFC+,FC-,FC+,Gov-,Gov+,HH-,HH+,RoW-,RoW+
item/sectors,,,,,,,,,,,
Output,P1,0,434543,0,24259,0,64991,0,82750,0,0
"Market output, output for final use and payments for other non-market output",P1O,0,0,0,0,0,13482,0,0,0,0
Market output,P11,0,427687,0,24027,0,2505,0,51502,0,0
Output for own final use,P12,0,6856,0,233,0,2905,0,23121,0,0
Other non-market output,P13,0,0,0,0,0,59581,0,8126,0,0
...,...,...,...,...,...,...,...,...,...,...,...
"Assets, gross - other structures",P51G_N1122G,0,0,0,0,0,0,0,0,0,0
"Assets, gross - other structures - chain linked volumes reference year 2010",P51G_N1122G_CLV2010,0,0,0,0,0,0,0,0,0,0
"Assets, gross - other buildings and structures",P51G_N112G,0,0,0,0,0,0,0,0,0,0
"Assets, gross - other buildings and structures - chain linked volumes reference year 2010",P51G_N112G_CLV2010,0,0,0,0,0,0,0,0,0,0
"Assets, gross - fixed assets by type of asset - chain linked volumes reference year 2010",P51G_N11G_CLV2010,0,0,0,0,0,0,0,0,0,0

### Part 2

In [10]:
#data.head()
df["Tot."] = -df["NFC-"] + df["NFC+"] - df["FC-"] + df["FC+"] - df["Gov-"] + df["Gov+"] - df["HH-"] + df["HH+"] - df["RoW-"] + df["RoW+"]

In [11]:
df['codes'] ='_' + df['codes'].astype(str)
df.head()

,codes,NFC-,NFC+,FC-,FC+,Gov-,Gov+,HH-,HH+,RoW-,RoW+,Tot.
item/sectors,,,,,,,,,,,,
Output,_P1,0,434543,0,24259,0,64991,0,82750,0,0,606543
"Market output, output for final use and payments for other non-market output",_P1O,0,0,0,0,0,13482,0,0,0,0,13482
Market output,_P11,0,427687,0,24027,0,2505,0,51502,0,0,505721
Output for own final use,_P12,0,6856,0,233,0,2905,0,23121,0,0,33115
Other non-market output,_P13,0,0,0,0,0,59581,0,8126,0,0,67707

In [12]:
# Transpose

datat = df.T
datat

item/sectors,Output,"Market output, output for final use and payments for other non-market output",Market output,Output for own final use,Other non-market output,Intermediate consumption,Final consumption expenditure,Individual consumption expenditure,Collective consumption expenditure,Actual final consumption,...,Total employment (thousands of hours worked) domestic concept,"Assets, gross - dwellings","Assets, gross - dwellings - chain linked volumes reference year 2010","Assets, gross - buildings other than dwellings","Assets, gross - buildings other than dwellings - chain linked volumes reference year 2010","Assets, gross - other structures","Assets, gross - other structures - chain linked volumes reference year 2010","Assets, gross - other buildings and structures","Assets, gross - other buildings and structures - chain linked volumes reference year 2010","Assets, gross - fixed assets by type of asset - chain linked volumes reference year 2010"
codes,_P1,_P1O,_P11,_P12,_P13,_P2,_P3,_P31,_P32,_P4,...,_EMP_HW_DC,_P51G_N111G,_P51G_N111G_CLV2010,_P51G_N1121G,_P51G_N1121G_CLV2010,_P51G_N1122G,_P51G_N1122G_CLV2010,_P51G_N112G,_P51G_N112G_CLV2010,_P51G_N11G_CLV2010
NFC-,0,0,0,0,0,261220,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
NFC+,434543,0,427687,6856,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
FC-,0,0,0,0,0,12019,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
FC+,24259,0,24027,233,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Gov-,0,0,0,0,0,20620,63287,38849,24438,0,...,1064125,0,0,0,0,0,0,0,0,0
Gov+,64991,13482,2505,2905,59581,0,0,0,0,0,...,1064125,0,0,0,0,0,0,0,0,0
HH-,0,0,0,0,0,29136,170351,170351,0,209200,...,0,0,0,0,0,0,0,0,0,0
HH+,82750,0,51502,23121,8126,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
RoW-,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
RoW+,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Tot.,606543,13482,505721,33115,67707,-322995,-233638,-209200,-24438,-209200,...,0,0,0,0,0,0,0,0,0,0

In [13]:
aggdict = aggregatedict = {
                'Wages': ['Wages and salaries'],
                'Social cont.': ["Employers' social contributions"],
                'VAT on products': ['Value added type taxes (VAT)'],
                'Imp tax on products': ['Taxes and duties on imports excluding VAT'], #VAT Gov+ and HH- 
                'Other taxes': ['Other taxes on production'] }

In [14]:
print(aggdict)

{'Wages': ['Wages and salaries'], 'Social cont.': ["Employers' social contributions"], 'VAT on products': ['Value added type taxes (VAT)'], 'Imp tax on products': ['Taxes and duties on imports excluding VAT'], 'Other taxes': ['Other taxes on production']}

In [15]:
new_data = {} 

# iterate through 'rows' (=transposed columns) and sum up 
for col in data.columns:
    
    for name,sub_groups in aggdict.items():
        new_data[name] = datat[sub_groups].sum(axis=1)
        #new_data[name] = data.loc['Eurostat code'][sub_groups].agg(','.join) 

#.loc['Eurostat code']
new_df = pd.DataFrame(new_data).T # create dataframe and transpose again 

# print new dataframe
print(new_df)

                     codes   NFC- NFC+   FC- FC+   Gov-   Gov+    HH-     HH+  \
Wages                 _D11  78628    0  6366   0  27794      0  11253  124267
Social cont.          _D12  15928    0  1649   0   6425      0   2282   26078
VAT on products      _D211      0    0     0   0      0  24507      0       0
Imp tax on products  _D212      0    0     0   0      0      0      0       0
Other taxes           _D29   6813    0  1603   0   1492  11035   1127       0

                     RoW-  RoW+   Tot.
Wages                1981  1754     -1
Social cont.          174   380      0
VAT on products         0     0  24507
Imp tax on products     0   344    344
Other taxes             0     0      0

In [16]:
df = new_df

In [17]:
df['codes'] = df['codes'].str.replace(' ', '_', 1)
df['codes'] = df['codes'].str[1:]

In [18]:
df.head()

,codes,NFC-,NFC+,FC-,FC+,Gov-,Gov+,HH-,HH+,RoW-,RoW+,Tot.
Wages,D11,78628,0,6366,0,27794,0,11253,124267,1981,1754,-1
Social cont.,D12,15928,0,1649,0,6425,0,2282,26078,174,380,0
VAT on products,D211,0,0,0,0,0,24507,0,0,0,0,24507
Imp tax on products,D212,0,0,0,0,0,0,0,0,0,344,344
Other taxes,D29,6813,0,1603,0,1492,11035,1127,0,0,0,0

In [21]:
df.at[4, 'HH-'] = '24507'

df.head()

,codes,NFC-,NFC+,FC-,FC+,Gov-,Gov+,HH-,HH+,RoW-,RoW+,Tot.
Wages,D11,78628,0,6366,0,27794,0,11253,124267,1981,1754,-1
Social cont.,D12,15928,0,1649,0,6425,0,2282,26078,174,380,0
VAT on products,D211,0,0,0,0,0,24507,0,0,0,0,24507
Imp tax on products,D212,0,0,0,0,0,0,0,0,0,344,344
Other taxes,D29,6813,0,1603,0,1492,11035,1127,0,0,0,0

In [19]:
df['NFC-'].describe()

count     5
unique    4
top       0
freq      2
Name: NFC-, dtype: int64

In [20]:
is_numeric_dtype(df['FC-'])

NameError: name 'is_numeric_dtype' is not defined